### ISSUE TITLE
Access denied for 

### ISSUE THREAD

**Issue by ajithreddygeth** [aws/eks-distro#44] opened 2020-12-01 18:29 UTC
**Access denied for distro.eks.amazonaws.com**

`This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>8C83AFB3556CA41A</RequestId>
<HostId>FmQKJB6vhsCm10o40VolmtGPVJAqJBoRReJGHfXM5iKzuxgsEWg97Pe7HzxjrnDoYreJroxQesg=</HostId>
</Error>`

_Hyperlink can be found on Readme_

**Comment by TerryHowe** [comment] 2020-12-01 18:34
We are working on this, thanks

**Comment by mhausenblas** [comment] 2020-12-01 18:37
Duplicate of #41, closing it.

**Comment by TerryHowe** [comment] 2020-12-01 19:37
https://distro.eks.amazonaws.com/ working now

**Comment by chandlerh** [comment] 2020-12-01 20:07
I'm going to close this as it's working now.

**Comment by chandlerh** [comment] 2020-12-01 20:07
Thanks again for reporting it!

**Closed by chandlerh** 2020-12-01 20:07 UTC
