### ISSUE TITLE
API server fails to come up for EKS-D v1.23.13-eks

### ISSUE THREAD

**Issue by nsagark** [aws/eks-distro#1523] opened 2022-12-08 18:22 UTC
**What happened**:
When creating an EKS-D cluster with version v1.23.13-eks the api server is failing to come up. When we do a docker inspect we are seeing below error. 

"Error": "OCI runtime create failed: container_linux.go:367: starting container process caused: exec: \"/usr/local/bin/go-runner\": stat /usr/local/bin/go-runner: no such file or directory: unknown"

**What you expected to happen**:
Expected api server and the cluster to get created. 

**How to reproduce it (as minimally and precisely as possible)**:
Create EKS-D cluster with version v1.23.13-eks

**Anything else we need to know?**:

**Environment**:
- EKS Distro Release Channel:
- EKS Distro Release: EKS-D  v1.23.13-eks

**Comment by TerryHowe** [comment] 2022-12-08 18:26
Sounds like a duplicate of https://github.com/aws/eks-distro/issues/1498

**Comment by markapruett** [comment] 2022-12-08 19:32
That one's been fixed in #1507 and will go out in our release next Thursday. You should only be seeing this if you ran that directly. In the meantime, you can override it on the command line with `docker run --entrypoint "/go-runner" or edit the manifest file.

**Comment by nsagark** [comment] 2022-12-16 14:07
@markapruett When will the fixed image be available to use?

**Comment by markapruett** [comment] 2022-12-16 14:11
The new images are now available on https://gallery.ecr.aws/eks-distro/kubernetes/go-runner

**Closed** 2022-12-19 14:52 UTC
Labels: external
